[package]
name = "get-colorchecker-values"
version = "0.2.4"
authors = ["hotgluebanjo <66244111+hotgluebanjo@users.noreply.github.com>"]
edition = "2021"

[dependencies]
image = "0.24.2"
structopt = "0.3.25"
